export const DEFAULT_LOADER_COLOR = '#3b82f6'
export const DEFAULT_LOADER_SIZE = 50
export const DEFAULT_LOADER_SPEED = 1
export const DEFAULT_LOADER_STROKE = 4
export const DEFAULT_LOADER_ORIENTATION = 'row'
export const DEFAULT_LOADER_ROTATION = 'clockwise'
export const DEFAULT_LOADER_SIZE_UNIT = 'px'
export const DEFAULT_LOADER_SPEED_UNIT = 's'
export const DEFAULT_LOADER_STROKE_UNIT = 'px'

const defaultValues = {
  DEFAULT_LOADER_COLOR,
  DEFAULT_LOADER_ORIENTATION,
  DEFAULT_LOADER_ROTATION,
  DEFAULT_LOADER_SIZE,
  DEFAULT_LOADER_SIZE_UNIT,
  DEFAULT_LOADER_SPEED,
  DEFAULT_LOADER_SPEED_UNIT,
  DEFAULT_LOADER_STROKE,
  DEFAULT_LOADER_STROKE_UNIT,
}

export default defaultValues
